### ISSUE TITLE
The contents of piped command and gof itself could be merged

### ISSUE THREAD

**Issue by ichizok** [mattn/gof#13]
When the output of piped command is delayed, `gof` will output also the own processing result and both are merged.

```
% ls -1
001
002
003
004
005
```

Do `sleep` explicitly before command (for fast I/O env):

```
% (sleep 1; find . -type f) | gof
```

Expected:
Only the result of `find` is listed after 1 sec; get 5 entries

Actual:
At first the result of `gof` is listed, and then (after 1 sec) the result of `find` is added; get 10 entries

```
  ./004
  ./005
  ./003
  ./002
  ./001
  004
  005
  003
  002
> 001
  10/10(0)
>
```

**Comment by mattn** [comment]
Thank you. https://github.com/mattn/gof/commit/61044917b977ea9ee28b78b75528ff6ac2a83bcb should fix this issue.

**Comment by ichizok** [comment]
Thank you!
