### ISSUE TITLE
add support for --expect=ctrl-t,ctrl-v-ctrl-x

### ISSUE THREAD

**Issue by prabirshrestha** [mattn/gof#8]
fzf supports passing `fzf --expect=ctrl-t,ctrl-v-ctrl-x`. It takes a comma supported key-bindings. This allows file to be selected using other keybindings besides enter.

If I press `ctrl-t` instead of `enter` it would create a file that looks like this.

```
ctrl-t
c:\Windows\System32\drivers\etc\hosts
```

same goes for `ctrl-v` and `ctrl-x`.

If use enter it would create the first line as blank line.

```

c:\Windows\System32\drivers\etc\hosts
```

Then in vim-fz, I can read the first line and see what it matches to. If it is `ctrl-t` I can open it in new tab, if it is `ctrl-x` I can open in horizontal split, if it is `ctrl-v` I can open in vertical split.

Would it be possible to support this use case?

**Comment by mattn** [comment]
please press CTRL-Z to select item.

**Comment by prabirshrestha** [comment]
I wasn't talking about multiselect.

Here is an example. I have a file `file.h` open. Now I want to open `file.c` and see it side by side. Currently it is impossible to do it using `gof` and `vim-fz` since it will always open in `file.h`. As a user I want to have a choice to either open in new tab, vsplit or split or in the existing buffer. `gof` needs to tell me what key was used to select. And `vim-fz` looks at that key which would be the first line and then opens the new file in appropriate window. Since `gof` is running in terminal the way to communicate back to vim would be to use the first line of the result.

**Comment by mattn** [comment]
Ah, fzf do nothing for the `--expect`, just output the what typed there right?

**Comment by prabirshrestha** [comment]
It doesn't nothing expect changing the stdout to this 

```
ctrl-t
c:\Windows\System32\drivers\etc\hosts
```

instead of this

```
c:\Windows\System32\drivers\etc\hosts
```

It is the vim plugin that does the magic on which buffer to open.
