### ISSUE TITLE
if -a is defined the first line in stdout should always be the key

### ISSUE THREAD

**Issue by prabirshrestha** [mattn/gof#9]
Currently when passing `-a` flag and we press enter it returns this stdout.

```
Line 1: c:\Windows\System32\drivers\etc\hosts
```

Can we change so the first line is always the key. Notice how line 1 is empty in the second example. That way I can know that the first line is always the key pressed and not the item. `fzf` uses empty to denote `enter` key.

```
Line 1:
Line 2: c:\Windows\System32\drivers\etc\hosts
```

**Comment by mattn** [comment]
I'm okay change behavior. Could you please send pull-request?

**Comment by prabirshrestha** [comment]
Sent the PR at https://github.com/mattn/gof/pull/10
